### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Herojhjh** [NL-4-DEVS/BedwarsPE#2]
[Tesseract] [06:46:51] CRITICAL> Unhandled exception executing command 'hub' in hub: Call to undefined method Driesboy\EggWars\EggWars::oyuncuArenadami()
[Tesseract] [06:46:51] CRITICAL> Error: "Call to undefined method Driesboy\EggWars\EggWars::oyuncuArenadami()" (EXCEPTION) in "/plugins/Eggwars/src/Driesboy/EggWars/Command/Hub" at line 20
[Tesseract] [06:47:35] CRITICAL> "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'Bedwars v2.3': Call to undefined method pocketmine\Player::setExpLevel() on Bluplayz\Bedwars
[Tesseract] [06:47:35] CRITICAL> Error: "Call to undefined method pocketmine\Player::setExpLevel()" (EXCEPTION) in "/plugins/BedwarsPE/src/Bluplayz/Bedwars" at line 488
[Tesseract] [06:47:36] CRITICAL> "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'Bedwars v2.3': Call to undefined method pocketmine\Player::setExpLevel() on Bluplayz\Bedwars
[Tesseract] [06:47:36] CRITICAL> Error: "Call to undefined method pocketmine\Player::setExpLevel()" (EXCEPTION) in "/plugins/BedwarsPE/src/Bluplayz/Bedwars" at line 488
[Tesseract] [06:47:38] CRITICAL> "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'Bedwars v2.3': Call to undefined method pocketmine\Player::setExpLevel() on Bluplayz\Bedwars
[Tesseract] [06:47:38] CRITICAL> Error: "Call to undefined method pocketmine\Player::setExpLevel()" (EXCEPTION) in "/plugins/BedwarsPE/src/Bluplayz/Bedwars" at line 488
[Tesseract] [06:47:40] CRITICAL> "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'Bedwars v2.3': Call to undefined method pocketmine\Player::setExpLevel() on Bluplayz\Bedwars
[Tesseract] [06:47:40] CRITICAL> Error: "Call to undefined method pocketmine\Player::setExpLevel()" (EXCEPTION) in "/plugins/BedwarsPE/src/Bluplayz/Bedwars" at line 488
[Tesseract] [06:47:41] CRITICAL> "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'Bedwars v2.3': Call to undefined method pocketmine\Player::setExpLevel() on Bluplayz\Bedwars
[Tesseract] [06:47:41] CRITICAL> Error: "Call to undefined method pocketmine\Player::setExpLevel()" (EXCEPTION) in "/plugins/BedwarsPE/src/Bluplayz/Bedwars" at line 488

**Comment by KitrosMC** [comment]
If you reloaded your server,it will be like this,You need to delete the plugin
